spring:
    http:
        encoding:
            charset:    UTF-8
    mvc:
        view:
            prefix:     /WEB-INF/jsp/
            suffix:     .jsp
    datasource:
        url: jdbc:mysql://localhost:3306/mangotv?serverTimezone=UTC
        username: mangotvadmin
        password: mangotvpass
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        # generate-ddl: true
        # database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  tomcat:
    uri-encoding: UTF-8